import tkinter as tk
from tkinter import messagebox
import random

# Flashcards data
# Flashcards data
flashcards = [("An attacker obtains bank account number and birth date by calling the victim.", "Vishing"),
("An attacker modifies a legitimate DNS server to resolve the IP address of a malicious site.", "DNS Spoofing"),
("An attacker intercepts all communication between a client and a web server.", "On-path"),
("Multiple attackers overwhelm a web server.", "DDoS"),
("A virus alert appears in your browser from Microsoft with a phone number to call for support.", "Hoax"),
("The best security control for a library web server and database server.", "Video Surveillance Location"),
("The best security control for library employee laptops.", "Full-Disk Encryption"),
("The best security control for library lending systems.", "Cable Lock"),
("The best security control for the computer room.", "Biometric Reader"),
("The best security control for the digital newspaper reading lab.", "Environmental Sensors"),
("The best secure network protocol for accepting customer purchases from your primary website.", "HTTPS"),
("The best secure network protocol for synchronizing the time across all of your devices.", "NTP (Network Time Protocol)"),
("The best secure network protocol for accessing your switch using a CLI terminal screen.", "SSH"),
("The best secure network protocol for talking with customers on scheduled conference calls.", "SRTP (Secure Real-Time Transport Protocol)"),
("The best secure network protocol for gathering metrics from routers at remote sites.", "SNMPv3 (Simple Network Management Protocol version 3)"),
("During the login process, your phone receives a text message with a one-time passcode.", "Something you have"),
("You enter your PIN to make a deposit into an ATM.", "Something you know"),
("You must sign a check-in sheet before entering a controlled area.", "Something you can do"),
("You can use your fingerprint to unlock the door to the data center.", "Something you are"),
("Your login will not work unless you are connected to the VPN.", "Somewhere you are"),
("You’ve hired a third-party to gather information about your company’s servers and data. The third-party will not have direct access to your internal network but can gather information from any other source.", "Passive footprinting"),
("Which protocols use TLS to provide secure communication?", "HTTPS and FTPS"),
("Which threat actors would be most likely to attack systems for direct financial gain?", "Organized crime"),
("Which data sources should be gathered to address file storage volatility in a security incident on a file server?", "Partition data and Temporary file systems"),
("A security team found a vulnerability associated with all A finance company is legally required to maintain seven years of tax records for all of their customers. Which of the following would be the BEST way to implement this requirement?", "Create a separate daily backup archive for all applicable tax records"),tration using external storage drives.", "Create an operating system security policy to prevent the use of removable media"),
("How to decrease the response time when addressing security incidents without hiring additional security engineers.", "SOAR"),
("Policies to handle data breaches include access records saved and archived, data access outside normal hours reported, data access inside the country, and consolidated logs. What should be implemented?", "Restrict login access by IP address and GPS location, Consolidate all logs on a SIEM, Enable time-of-day restrictions on the authentication server"),
("What can be observed from this firewall log information?", "A download was blocked from a web server"),
("A user connects to a third-party website and receives a message: Your connection is not private. NET::ERR_CERT_INVALID. Which attack is most likely the reason for this message?", "On-path"),
("The best way to provide a website login using existing credentials from a third-party site.", "Federation"),
("A system administrator needs to know how often the firewall hardware is expected to fail between repairs. Which term best describes this information?", "MTBF"),
("An attacker calls a company's help desk and pretends to be the director, asking to reset their password for an important meeting. What kind of attack is this?", "Social engineering"),
("The company's network team needs to support additional authentication protocols inside an encrypted tunnel. Which protocol meets this requirement?", "EAP-TTLS"),
("Commonly provided by a CASB (Cloud Access Security Broker).", "List of applications in use and Verification of encrypted data transfers"),
("The embedded OS in a time clock appliance causes a constant reboot due to a file system error during startup. Which issue best describes this?", "Race condition"),
("Password policies do not include restrictions on attempts and periodic changes. What would correct these issues?", "Password expiration and Password lockout"),
("What kind of security control is associated with a login banner?", "Deterrent"),
("Expected on a non-credentialed vulnerability scan report.", "The version of web server software in use"),
("A set of steps for processing orders if the primary Internet connection fails. Which term best describes these steps?", "Continuity of operations"),
("The best way to protect against data exfiltration from malicious phone charging stations.", "USB data blocker"),
("The best choice to protect data stored on laptops used in the field.", "SED (Self-Encrypting Drive)"),
("A full backup is performed on Monday, with incremental backups on Tuesday to Friday. How many backup sets are required for a full recovery on Thursday?", "4"),
("The best way to establish security policy rules for corporate mobile devices, including auto-lock, traceable location, and separation of user information.", "MDM (Mobile Device Management)"),
("A vulnerability scan doesn't list any vulnerabilities for Windows servers despite a recent significant vulnerability. What best describes this result?", "False negative"),
("Additional authentication controls to add to existing infrastructure.", "TOTP and Smart Card"),
("To authenticate with personal username and password when connecting to the company's wireless network. Which configuration should be used?", "802.1X"),
("Tools to view the source of a web page and search for a specific filename in the HTML.", "grep and curl"),
("Access control model when a user assigns rights and permissions to a file and adds others for read-only access.", "DAC (Discretionary Access Control)"),
("A remote user receives a text message requesting login details to the corporate VPN server. What best describes this message?", "Smishing"),
("Separation of duties to enforce a store policy requiring floor manager approval for gift certificate transactions.", "Require an approval PIN for the cashier and a separate approval PIN for the manager"),
("True statements about rainbow tables.", "Different tables are required for different hashing methods and A rainbow table won’t be useful if the passwords are salted"),
("A decrease in visitors to a bank's website is due to users being directed to a different IP address. What attack is this?", "DNS poisoning"),
("Which cloud deployment model shares resources between a private virtualized data center and externally available cloud services?", "Hybrid"),
("The best way to verify that systems cannot be accessed by former employees after seasonal employment ends.", "Create a report that shows all authentications for a 24-hour period"),
("A new access point is installed, but only some devices can connect. Which security feature is most likely enabled?", "MAC filtering"),
("The command used to gather information showing TCP6 connections and their states.", "netstat"),
("An attack where specially crafted packets disable a server and require a reboot. Which attack is this?", "DDoS"),
("A data breach has occurred, and a security administrator is building new servers and systems to get financial systems back online. Which part of the incident response process is this?", "Reconstitution"),
("The best way to manage security policies on a new PaaS service.", "CASB (Cloud Access Security Broker)"),
("A significant vulnerability in a newly installed firewall is identified, but the vendor has no plans to patch it. Which term best describes this issue?", "Lack of vendor support"),
("A disaster recovery exercise during an annual meeting involves discussing the logistics and processes to resolve a simulated disaster. Which term best describes this exercise?", "Tabletop exercise"),
("The best way to identify all computers on the company network infected with a specific malware variant.", "DNS sinkhole"),
("A system administrator removes a device suspected of malware infection from the network and disconnects all USB flash drives. Which incident response step is this?", "Containment"),
("How to ensure all data on a mobile device is unrecoverable if lost or stolen.", "Remote wipe"),
("Which log files provide information regarding memory contents of servers infected with ransomware?", "Dump logs"),
("Which part of the PC startup process verifies the digital signature of the OS kernel?", "Trusted Boot"),
("Best description of two-factor authentication.", "A Windows Domain requires a username, password, and smart card"),
("Which deployment model addresses concerns of managing mobile devices, introducing risk, and varied device types for a new mobile application?", "COPE (Corporate Owned, Personally Enabled)"),
("Which term best describes installing a UPS for a new data center?", "Compensating control"),
("Best technology for tracking progress of parts on an assembly line.", "Blockchain"),
("Order of data collection to gather the most volatile data before powering down database servers in response to a potential security breach.", "CPU registers, memory, temporary files, remote monitoring data"),
("Use of SHA256 hash value shown with a Linux distribution download link.", "Verifies that the file was not corrupted during the file transfer"),
("The best way to ensure login access is available only if a person is physically within the same building as the server.", "Biometric scanner"),
("A vulnerability scanner finds a database available for anyone to query without authentication. Which vulnerability is this?", "Open permissions"),
("An email offering a cash bonus for completing an internal training course requires a login to an external server. What best describes this email?", "Phishing"),
("Risk management strategy involving the purchase and installation of an NGFW.", "Mitigation"),
("The best way to confirm the secure baseline of a deployed application instance.", "Perform an integrity measurement"),
("A member of the accounting team was out of the office, delaying an important financial transfer. Which term describes a method to prevent this delay?", "Job rotation"),
("Log information showing sessions from a single IP address with TTL equal to zero to the firewall and DMZ server. What best describes this?", "Someone is performing a traceroute to the DMZ server"),
("An attacker sends more information than expected in a single API call, allowing execution of arbitrary code. Which attack is this?", "Buffer overflow"),
("Key to place into escrow when encrypting confidential materials on a central server.", "Private key"),
("The best authentication process for remote site deployment, requiring credentials in the morning and no additional requests during the day.", "Kerberos"),
("Best way to segment a corporate network and manufacturing floor using the same physical switch without additional hardware.", "Create separate VLANs for the corporate network and the manufacturing floor"),
("A home user can't print to their local network printer when connected to the corporate VPN. Which issue is most likely the reason?", "The VPN tunnel is configured for full tunnel"),
("The most likely reason for placing servers in a Faraday cage in a data center.", "Protect the servers against any unwanted electromagnetic fields"),
("A vulnerability previously patched returns after a recent patch. Which method should be implemented to prevent this issue?", "Continuous monitoring"),
("The best way to ensure unique hashes are used with an application login process.", "Salting"),
("Which cryptographic method adds trust to a digital certificate?", "Digital signature"),
("An MSP is designing a new server room for a large company. Which of the following should be included in the design to provide redundancy? (Select TWO)", "RAID arrays, Dual power supplies"),
("An organization maintains a large database of customer information for sales tracking and customer support. Which person in the organization would be responsible for managing the access rights to this data?", "Data owner"),
("An organization’s content management system (CMS) currently labels files and documents as “Unclassified” and “Restricted.” On a recent update to the CMS, a new classification type of “PII” was added. Which of the following would be the MOST likely reason for this addition?", "Expanded privacy compliance"),
("A corporate security team would like to consolidate and protect the private keys across all of their web servers. Which of these would be the BEST way to securely store these keys?", "Use an HSM"),
("Jennifer is reviewing this security log from her IPS. Which of the following can be determined from this log information? (Select TWO)", "The alert was generated from an embedded script, The attacker’s IP address is 222.43.112.74"),
("Which of the following describes a monetary loss if one event occurs?", "SLE"),
("A user with restricted access has typed this text in a search field of an internal web-based application: USER77' OR '1'='1. After submitting this search request, all of the database records are displayed on the screen. Which of the following would BEST describe this search?", "SQL injection"),
("A user has opened a helpdesk ticket complaining of poor system performance, excessive pop-up messages, and the cursor moving without anyone touching the mouse. This issue began after they opened a spreadsheet from a vendor containing part numbers and pricing information. Which of the following is MOST likely the cause of this user's issues?", "RAT"),
("A web-based manufacturing company processes monthly charges to credit card information saved in the customer's profile. Which of the following standards would be required to maintain this payment information?", "PCI DSS"),
("A security manager has created a report showing intermittent network communication from external IP addresses to certain workstations on the internal network. These traffic patterns occur at random times during the day. Which of the following would be the MOST likely reason for these traffic patterns?", "Backdoor"),
("The security policies in a manufacturing company prohibit the transmission of customer information. However, a security administrator has received an alert that credit card numbers were transmitted as an email attachment. Which of the following was the MOST likely source of this alert message?", "DLP"),
("A security administrator has configured a virtual machine in a screened subnet with a guest login account and no password. Which of the following would be the MOST likely reason for this configuration?", "The server is a honeypot for attracting potential attackers"),
("A company's outgoing email server currently uses SMTP with no encryption. The security administrator would like to implement encryption between email clients without changing the existing server-to-server communication. Which of the following would be the BEST way to implement this requirement?", "Require the use of S/MIME"),
("A company would like to securely deploy applications without the overhead of installing a virtual machine for each system. Which of the following would be the BEST way to deploy these applications?", "Containerization"),
("A company has just purchased a new application server, and the security director wants to determine if the system is secure. The system is currently installed in a test environment and will not be available to users until the rollout to production next week. Which of the following would be the BEST way to determine if any part of the system can be exploited?", "Penetration test"),
("A security administrator has performed an audit of the organization's production web servers, and the results have identified banner information leakage, web services running from a privileged account, and inconsistencies with SSL certificates. Which of the following would be the BEST way to resolve these issues?", "Server hardening"),    ("A shipping company stores information in small regional warehouses around the country. The company keeps an IPS online at each warehouse to watch for suspicious traffic patterns. Which of the following would BEST describe the security control used at the warehouse?", "Detective"),
("The Vice President of Sales has asked the IT team to create daily backups of the sales data. The Vice President is an example of a:", "Data owner"),
("A security engineer is preparing to conduct a penetration test. Part of the preparation involves reading through social media posts for information about a third-party website. Which of the following describes this practice?", "OSINT"),
("A company would like to automate their response when a virus is detected on company devices. Which of the following would be the BEST way to implement this function?", "SOAR"),
("A user in the accounting department has received an email from the CEO requesting payment for a recently purchased tablet. However, there doesn't appear to be a purchase order associated with this request. Which of the following would be the MOST likely attack associated with this email?", "Invoice scam"),
("A company has been informed of a hypervisor vulnerability that could allow users on one virtual machine to access resources on another virtual machine. Which of the following would BEST describe this vulnerability?", "VM escape"),
("While working from home, users are attending a project meeting over a web conference. When typing in the meeting link, the browser is unexpectedly directed to a different website than the web conference. Users in the office do not have any issues accessing the conference site. Which of the following would be the MOST likely reason for this issue?", "DNS poisoning"),
("A company is launching a new internal application that will not start until a username and password is entered and a smart card is plugged into the computer. Which of the following BEST describes this process?", "Authentication"),
("An online retailer is planning a penetration test as part of their PCI DSS validation. A third-party organization will be performing the test, and the online retailer has provided the Internet-facing IP addresses for their public web servers but no other details. What penetration testing methodology is the online retailer using?", "Partially known environment"),
("A manufacturing company makes radar used by commercial and military organizations. A recently proposed policy change would allow the use of mobile devices inside the facility. Which of the following would be the MOST significant security issue associated with this change in policy?", "Photo and video use"),
("A company is designing an application that will have a high demand and will require significant computing resources during the summer. During the winter, there will be little to no application use and resource use should be minimal. Which of these characteristics BEST describe this application requirement?", "Elasticity"),
("Vala, a security analyst, has received an alert from her IPS regarding active exploit attempts from the Internet. Which of the following would provide detailed information about these exploit attempts?", "Wireshark"),
("A user in the accounting department would like to send a spreadsheet with sensitive information to a list of third-party vendors. Which of the following could be used to transfer this spreadsheet to the vendors?", "FTPS"),
("A system administrator would like to segment the network to give the marketing, accounting, and manufacturing departments their own private network. The network communication between departments would be restricted for additional security. Which of the following should be configured on this network?", "VLAN"),
("A technician at an MSP has been asked to manage devices on third-party private network. The technician needs command line access to internal routers, switches, and firewalls. Which of the following would provide the necessary access?", "Jump server"),
("A transportation company is installing new wireless access points in their corporate offices. The manufacturer estimates that the access points will operate an average of 100,000 hours before a hardware-related outage. Which of the following describes this estimate?", "MTBF"),
("A security administrator has been asked to create a policy that would prevent access to a secure area of the network. All users who are not physically located in the corporate headquarters building would be prevented from accessing this area. Which of these should the administrator use?", "Geofencing"),
("Which of the following would be considered multi-factor authentication?", "PIN and fingerprint"),
("Sam, a security administrator, is configuring the authentication process used by technicians when logging into a router. Instead of using accounts that are local to the router, Sam would like to pass all login requests to a centralized database. Which of the following would be the BEST way to implement this requirement?", "RADIUS"),
("A recent audit has determined that many IT department accounts have been granted Administrator access. The audit recommends replacing these permissions with limited access rights. Which of the following would BEST describe this policy?", "Least privilege"),
("A recent security audit has discovered email addresses and passwords located in a packet capture. Which of the following did the audit identify?", "Insecure protocols"),
("A company has connected their wireless access points and have enabled WPS. Which of the following security issues would be associated with this configuration?", "Brute force"),
("An organization has traditionally purchased insurance to cover a ransomware attack, but the costs of maintaining the policy have increased above the acceptable budget. The company has now decided to cancel the insurance policies and deal with ransomware issues internally. Which of the following would best describe this action?", "Acceptance"),
("Which of these threat actors would be the MOST likely to deface a website to promote a political agenda?", "Hacktivist"),
("An IPS report shows a series of exploit attempts were made against externally facing web servers. The system administrator of the web servers has identified a number of unusual log entries on each system. Which of the following would be the NEXT step in the incident response process?", "Disconnect the web servers from the network"),
("A security administrator is viewing the logs on a laptop in the shipping and receiving department and identifies these events: 8:55:30 AM | D:\\Downloads\\ChangeLog-5.0.4.scr | Quarantine Success 9:22:54 AM | C:\\Program Files\\Photo Viewer\\ViewerBase.dll | Quarantine Failure 9:44:05 AM | C:\\Sales\\Sample32.dat | Quarantine Success. Which of the following would BEST describe the circumstances surrounding these events?", "The antivirus application identified three viruses and quarantined two viruses"),
("In the past, an organization has relied on the curated Apple App Store to avoid the issues associated with malware and insecure applications. However, the IT department has discovered an iPhone in the shipping department that includes applications that are not available on the Apple App Store. How did the shipping department user install these apps on their mobile device?", "Sideloading"),
("A security administrator is designing a storage array that would maintain an exact replica of all data without striping. The array needs to operate normally if a single drive was to fail. Which of the following would be the BEST choice for this storage system?", "RAID 1"),
("A transportation company has moved their reservation system to a cloud-based infrastructure. The security manager would like to monitor data transfers, identify potential threats, and ensure that all data transfers are encrypted. Which of the following would be the BEST choice for these requirements?", "CASB"),
("Which of the following control types is associated with a bollard?", "Physical"),
("Jack, a hacker, has identified a number of devices on a corporate network that use the username of “admin” and the password of “admin.” Which vulnerability describes this situation?", "Default configuration"),
("A security administrator attends an annual industry convention with other security professionals from around the world. Which of the following attacks would be MOST likely in this situation?", "Watering hole"),
("A transportation company headquarters is located in an area with frequent power surges and outages. The security administrator is concerned about the potential for downtime and hardware failures. Which of the following would provide the most protection against these issues? Select TWO.", "UPS, Dual power supplies"),
("An organization has developed an in-house mobile device app for order processing. The developers would like the app to identify revoked server certificates without sending any traffic over the corporate Internet connection. Which of the following MUST be configured to allow this functionality?", "OCSP stapling"),
("Sam, a security administrator, is configuring an IPsec tunnel to a remote site. Which protocol should she enable to protect all of the data traversing the VPN tunnel?", "ESP"),
("A Linux administrator has received a ticket complaining of response issues with a database server. After connecting to the server, the administrator views this information: Filesystem Size Used Avail Use% Mounted on /dev/xvda1 158G 158G 0 100% /. Which of the following would BEST describe this information?", "Resource exhaustion"),
("Which of the following would limit the type of information a company can collect from their customers?", "Minimization"),
("A security administrator has identified a DoS attack against the company's web server from an IPv4 address on the Internet. Which of the following security tools would provide additional details about the attacker’s location? (Select TWO)", "tracert, dig"),
("A hacker is planning an attack on a large corporation. Which of the following would provide the attacker with details about the company’s domain names and IP addresses?", "Open-source intelligence"),
("A security administrator is designing a network to be PCI DSS compliant. Which of the following would be the BEST choice to provide this compliance?", "Perform regular audits and vulnerability scans"),
("A security administrator would like to test a server to see if a specific vulnerability exists. Which of the following would be the BEST choice for this task?", "Metasploit"),
("A company has rolled out a new application that requires the use of a hardware-based token generator. Which of the following would be the BEST description of this access feature?", "Something you have"),
("A company has signed an SLA with an Internet service provider. Which of the following would BEST describe the content of this SLA?", "The service provider will provide 99.999% uptime"),
("An attacker has created many social media accounts and is posting information in an attempt to get the attention of the media. Which of the following would BEST describe this attack?", "Influence campaign"),
("Which of the following would be the BEST way to protect credit card account information when performing real-time purchase authorizations?", "Tokenization"),
("The network design of an online women's apparel company includes a primary data center in the United States and secondary data centers in London and Tokyo. Customers place orders online via HTTPS to servers at the closest data center, and these orders and customer profiles are then centrally stored in the United States data center. The connections between all data centers use Internet links with IPsec tunnels. Fulfillment requests are sent from the United States data center to shipping locations in the customer’s country. Which of the following should be the CIO’s MOST significant security concern with this existing network design?", "Customer information is transferred between countries"),
("A government transport service has installed access points that support WPA3. Which of the following technologies would provide enhanced security for PSK while using WPA3?", "SAE"),
("A security administrator has found a keylogger installed alongside an update of accounting software. Which of the following would prevent the transmission of the collected logs?", "Block all unknown outbound network traffic at the Internet firewall"),
("A user in the marketing department is unable to connect to the wireless network. After authenticating with a username and password, the user receives this message: The AP is configured with WPA3 encryption and 802.1X authentication. -- -- -- The connection attempt could not be completed. The Credentials provided by the server could not be validated. Radius Server: radius.example.com Root CA: Example.com Internal CA Root Certificate -- -- -- Which of the following is the MOST likely reason for this login issue?", "The client computer does not have the proper certificate installed"),
("A security administrator has created a new policy that prohibits the use of MD5 hashes due to collision problems. Which of the following describes the reason for this new policy?", "Two different messages share the same hash"),
("Jack, a security administrator, has been tasked with hardening all of the internal web servers to prevent on-path attacks and to protect the application traffic from protocol analysis. These requirements should be implemented without changing the configuration on the client systems. Which of the following should Jack include in his project plan? (Select TWO)", "Use HTTPS over port 443 for all server communication, Create a web server certificate and sign it with the internal CA"),
("A security administrator has identified the installation of a RAT on a database server and has quarantined the system. Which of the following should be followed to ensure that the integrity of the evidence is maintained?", "Chain of custody"),
("Which of the following would be the BEST option for application testing in an environment that is completely separated from the production network?", "Air gap"),
("To process the company payroll, a manager logs into a third-party browser-based application and enters the hours worked for each employee. The financial transfers and physical check mailings are all provided by the third-party company. The manager does not maintain any servers or virtual machines within his company. Which of the following would BEST describe this application model?", "SaaS"),
("Which of the following BEST describes the modification of application source code that removes white space, shortens variable names, and rearranges the text into a compact format?", "Obfuscation"),
("Which of the following vulnerabilities would be the MOST significant security concern when protecting against a competitor?", "Lack of patch updates on an Internet-facing database server"),
("A third-party vulnerability scan reports that a company's web server software version is susceptible to a memory leak vulnerability. Which of the following would be the expected result if this vulnerability was exploited?", "DDoS"),
("Which of the following would be the BEST way to determine if files have been modified after the forensics data acquisition process has occurred?", "Create a hash of the data"),
("A system administrator is implementing a password policy that would require letters, numbers, and special characters to be included in every password. Which of the following controls MUST be in place to enforce this password policy?", "Complexity"),
("Which of the following applies scientific principles to provide a post-event analysis of an intrusion?", "Diamond model"),
("Which of the following would be the MOST likely result of plaintext application communication?", "Replay attack"),
("Daniel, a system administrator, believes that certain configuration files on a Linux server have been modified from their original state. Daniel has reverted the configurations to their original state, but he would like to be notified if they are changed again. Which of the following would be the BEST way to provide this functionality?", "File integrity check"),
("A security administrator is updating the network infrastructure to support 802.1X authentication. Which of the following would be the BEST choice for this configuration?", "LDAP"),
("Your company owns a purpose-built appliance that doesn’t provide any access to the operating system and doesn't provide a method to upgrade the firmware. Which of the following describes this appliance?", "Embedded system"),
("Last month, a finance company disposed of seven-year-old printed customer account summaries that were no longer required for auditing purposes. A recent online search has now found that images of these documents are available as downloadable torrents. Which of the following would MOST likely have prevented this information breach?", "Pulping"),
("A security manager believes that an employee is using their laptop to circumvent the corporate Internet security controls through the use of a cellular hotspot. Which of the following could be used to validate this belief? (Select TWO)", "UTM appliance logs, Host-based firewall logs"),
("An application developer is creating a mobile device app that will include extensive encryption and decryption. Which of the following technologies would be the BEST choice for this app?", "Elliptic curve"),
("Which of the following would be a common result of a successful vulnerability scan?", "A list of Microsoft patches that have not been applied to a server"),
("A security administrator is researching an issue with conference room users at a remote site. When connected to the wireless network, users receive an IP address that is not part of the corporate addressing scheme. Communication over this network also appears to have slower performance than the wireless connections elsewhere in the building. Which of the following would be the MOST likely reason for these issues?", "Rogue access point"),
("A company has identified a compromised server, and the security team would like to know if an attacker has used this device to move between systems. Which of the following would be the BEST way to provide this information?", "NetFlow logs"),
("A system administrator has protected a set of system backups with an encryption key. The system administrator used the same key when restoring files from this backup. Which of the following would BEST describe this encryption type?", "Symmetric"),
("A new malware variant takes advantage of a vulnerability in a popular email client. Once installed, the malware forwards all email attachments containing credit card information to an external email address. Which of the following would limit the scope of this attack?", "Scan outgoing traffic with DLP"),
("An organization has identified a security breach and has removed the affected servers from the network. Which of the following is the NEXT step in the IR process?", "Eradication"),
("A manager of the accounting department would like to minimize the opportunity for embezzlement and fraud from any of the current accounting team employees. Which of these policies should the manager use to avoid these issues?", "Mandatory vacations"),
("Which of the following would be the MAIN reasons why a system administrator would use a TPM when configuring full disk encryption? (Select TWO)", "Uses burned-in cryptographic keys, Includes built-in protections against brute-force attacks"),
("A security administrator would like to create an access control where each file or folder is assigned a security clearance level, such as “confidential” or “secret.” The security administrator would then assign a maximum security level to each user. What type of access control would be used in this network?", "Mandatory"),
("Cameron, a security administrator, is reviewing a report that shows a number of devices on internal networks attempting to connect with servers in the data center network. Which of the following security controls should Cameron add to prevent internal systems from accessing data center devices?", "ACL"),
("A financial services company is headquartered in an area with a high occurrence of tropical storms and hurricanes. Which of the following would be MOST important when restoring services disabled by a storm?", "Disaster recovery plan"),
("A user in the mail room has reported an overall slowdown of his shipping management software. An anti-virus scan did not identify any issues, but a more thorough malware scan identified a kernel driver that was not part of the original operating system installation. Which of the following malware was installed on this system?", "Rootkit"),
("A virus scanner has identified a macro virus in a word processing file attached to an email. Which of the following information could be obtained from the metadata of this file?", "Date and time when the file was created"),
("If a person is entering a data center facility, they must check-in before they are allowed to move further into the building. People who are leaving must be formally checked-out before they are able to exit the building. Which of the following would BEST facilitate this process?", "Access control vestibule"),
("A security administrator has discovered that an employee has been exfiltrating confidential company information by embedding the data within image files and emailing the images to a third-party. Which of the following would best describe this activity?", "Steganography"),
("A security engineer is running a vulnerability scan on their own workstation. The scanning software is using the engineer's account access to perform all scans. What type of scan is running?", "Credentialed"),
("Which of the following would be the best way to describe the estimated number of laptops that might be stolen in a fiscal year?", "ARO")
("A finance company is legally required to maintain seven years of tax records for all of their customers. Which of the following would be the BEST way to implement this requirement?", "Create a separate daily backup archive for all applicable tax records"),
("A system administrator is designing a data center for an insurance company’s new public cloud and would like to restrict user access to sensitive data. Which of the following would provide ongoing visibility, data security, and control of cloud-based applications?", "CASB"),
("A device is exhibiting intermittent connectivity when viewing remote web sites. A security administrator views the local device ARP table. Which of the following would be the MOST likely explanation of this connectivity issue?", "ARP poisoning"),
("A security administrator has identified an internally developed application that allows users to modify SQL queries through a web-based front-end. To prevent this modification, the administrator has recommended that all queries be completely removed from the application front-end and placed onto the back-end of the application server. Which of the following would describe this implementation?", "Stored procedures"),
("A system administrator is implementing a fingerprint scanner to provide access to the data center. Which of these metrics should be kept at a minimum in order to prevent unauthorized persons from accessing the data center?", "FAR"),
("The IT department of a transportation company maintains an on-site inventory of chassis-based network switch interface cards. If a failure occurs, the on-site technician can replace the interface card and have the system running again in sixty minutes. Which of the following BEST describes this recovery metric?", "MTTR"),
("A company maintains a server farm in a large data center. These servers are for internal use only and are not accessible externally. The security team has discovered that a group of servers was breached before the latest updates were applied. Breach attempts were not logged on any other servers. Which of these threat actors would be MOST likely involved in this breach?", "Insider"),("An organization has contracted with a third-party to perform a vulnerability scan of their Internet-facing web servers. The report shows that the web servers have multiple Sun Java Runtime Environment (JRE) vulnerabilities, but the server administrator has verified that JRE is not installed. Which of the following would be the BEST way to handle this report?", "Ignore the JRE vulnerability alert"),
("A user downloaded and installed a utility for compressing and decompressing files. Immediately after installing the utility, the user’s overall workstation performance degraded, and it now takes twice as much time to perform any tasks on the computer. Which of the following is the BEST description of this malware infection?", "Trojan"),
("Which of the following is the process for replacing sensitive data with a non-sensitive and functional placeholder?", "Tokenization"),
("A security administrator has installed a new firewall to protect a web server VLAN. The application owner requires that all web server sessions communicate over an encrypted channel. Which of these rules should the security administrator include in the firewall rulebase? (Select TWO)", "Source: ANY, Destination: ANY, Protocol: TCP, Port: 80, Deny"),
("Which of these would be used to provide multi-factor authentication?", "Smart card with picture ID"),
("An IT manager is leading a project to implement a global standard for a privacy information management system. Which of these standards would BEST apply to this project?", "ISO 27701"),
("A company’s security cameras have identified an unknown person walking into a fenced disposal area in the back of the building and then leaving with a box containing printed documents. Which of the following attacks is this person attempting?", "Dumpster diving"),
("A technology company is manufacturing a military-grade radar tracking system that can instantly identify any nearby unmanned aerial vehicles (UAVs). The UAV detector must be able to instantly identify and react to a vehicle without delay. Which of the following would BEST describe this tracking system?", "RTOS"),
("A private company uses an SSL proxy to examine the contents of an encrypted application during transmission. How could the application developers prevent the use of this proxy examination in the future?", "Certificate pinning"),
("A security administrator is concerned that a user may have installed a rogue access point on the corporate network. Which of the following could be used to confirm this suspicion?", "Switch log"),
("During a ransomware outbreak, an organization was forced to rebuild database servers from known good backup systems. In which of the following incident response phases were these database servers brought back online?", "Recovery"),
("Which of the following cloud deployments would include CPU, storage, and networking, but not include any operating system or application?", "IaaS"),
("A network IPS has created this log entry. Which of the following would describe this log entry?", "SQL injection"),
("An incident response team would like to validate their disaster recovery plans without making any changes to the infrastructure. Which of the following would be the best course of action?", "Tabletop exercise"),
("A system administrator has installed a new firewall between the corporate user network and the data center network. When the firewall is turned on with the default settings, users complain that the application in the data center is no longer working. Which of the following would be the BEST way to correct this application issue?", "Create firewall rules that match the application traffic flow"),
("Which of these would be used to provide HA for a web-based database application?", "UPS"),
("Each year, a certain number of laptops are lost or stolen and must be replaced by the company. Which of the following would describe the total cost the company spends each year on laptop replacements?", "ALE"),
("A network administrator is viewing a log file from a web server. Which of the following would be the BEST way to prevent this attack?", "Input validation"),
("Sam, a user in the purchasing department, would like to send an email to Jack. Which of these should Sam use that would allow Jack to verify the sender of the email?", "Digitally sign it with Sam’s private key"),
("The contract of a long-term temporary employee is ending. Which of these would be the MOST important part of the off-boarding process?", "Archive the decryption keys associated with the user account"),
("Daniel, a cybersecurity analyst, has been asked to respond to a denial of service attack against a web server. Daniel first collects information in the ARP cache, then a copy of the server’s temporary file system, and finally system logs from the web server. What part of the forensics gathering process did Daniel follow?", "Order of volatility"),
("An attacker was able to download ten thousand company employee login credentials containing usernames and hashed passwords. Less than an hour later, a list containing all ten thousand usernames and passwords in plain text were posted to an online file storage repository. Which of the following would BEST describe how this attacker was able to post this information?", "Weak cipher suite"),
("A security administrator is researching the methods used by attackers to gain access to web servers. Which of the following would provide additional information about these techniques?", "Honeypot"),
("A server administrator is building a new web server and needs to provide operating system access to the web server executable. Which of the following account types should be configured?", "Service"),
("A company is implementing a series of automated processes when responding to a security event. Which of the following would provide a linear checklist of steps to perform?", "Runbook"),
("A transportation company maintains a scheduling application and a database in a virtualized cloud-based environment. Which of the following would be the BEST way to backup these services?", "Snapshot"),
("In an environment using discretionary access controls, which of these would control the rights and permissions associated with a file or directory?", "Owner"),
("A security administrator has installed a network-based DLP solution to determine if file transfers contain PII. Which of the following describes the data during the file transfer?", "In-transit"),
("A medical imaging company would like to connect all remote locations together with high speed network links. The network connections must maintain high throughput rates and must always be available during working hours. In which of the following should these requirements be enforced with the network provider?", "Service level agreement"),
("A security administrator would like to encrypt all telephone communication on the corporate network. Which of the following protocols would provide this functionality?", "SRTP"),
("A security administrator is preparing a phishing email that will be sent to employees as part of a periodic security test. The email is spoofed to appear as an unknown third-party and asks employees to immediately click a link or their state licensing will be revoked. Which of these social engineering principles are used by this email?", "Authority and Urgency"),
("A security administrator would like to minimize the number of certificate status checks made by web site clients to the certificate authority. Which of the following would be the BEST option for this requirement?", "OCSP stapling"),
("A company is concerned their EDR solution will not be able to stop more advanced ransomware variants. Technicians have created a backup and restore utility that will get most systems up and running less than an hour after an attack. What type of security control is associated with this restore process?", "Compensating"),
("To upgrade an internal application, the development team provides the operations team with a patch and instructions for backing up, patching, and reverting the patch if needed. The operations team schedules a date for the upgrade, informs the business divisions, and tests the upgrade process after completion. Which of the following describes this process?", "Change management"),
("A company is implementing a public file-storage and cloud-based sharing service, but does not want to build a separate authentication front-end. Instead, the company would like users to authenticate with an existing account on a trusted third-party web site. Which of the following should the company implement?", "Federation"),
("A system administrator is viewing this output from Microsoft’s System File Checker: Repairing corrupted file. Which of the following malware types is the MOST likely cause of this output?", "Rootkit"),
("What type of vulnerability would be associated with this log information? GET http://example.com/show.asp?view=../../Windows/system.ini HTTP/1.1", "Directory traversal"),
("A developer has created an application that will store password information in a database. Which of the following BEST describes a way of protecting these credentials by adding random data to the password?", "Salting"),
("Which of the following processes merges developed code, tests for issues, and automatically moves the newly developed application to production without any human intervention?", "Continuous deployment"),
("Which of the following BEST describes a risk matrix?", "A visual summary of a risk assessment"),
("A security administrator would like to implement an authentication system that uses cryptographic tickets to validate users. Which of the following would provide this functionality?", "Kerberos"),
("Richard is reviewing this information from an IPS log: HTTP Suspicious Webdav OPTIONS Method Request. Which of the following can be associated with this log information?", "The source of the attack is 10.1.111.7 and The attacker sent an unusual HTTP packet to trigger the IPS"),
("A company has contracted with a third-party to provide penetration testing services. The service includes a port scan of each externally-facing device. This is an example of:", "Active footprinting"),
("An access point in a corporate headquarters office has the following configuration: Security Mode: WEP-PSK. Which of the following would apply to this configuration?", "Weak encryption"),
("An application does not properly release unused memory, and eventually it grows so large that it uses all available memory. Which of the following would describe this issue?", "Memory leak"),
("A company is receiving complaints of slowness and disconnections to their Internet-facing web server. A network administrator monitors the Internet link and finds excessive bandwidth utilization from thousands of different IP addresses. Which of the following would be the MOST likely reason for these performance issues?", "DDoS"),
("A penetration tester is researching a company using information gathered from user profiles and posts on a social media site. Which of the following would describe this activity?", "Passive footprinting"),
("A system administrator is configuring an IPsec VPN to a remote location and would like to ensure that the VPN provides confidentiality for both the original IP header and the data. Which of the following should be configured on the VPN?", "ESP"),
("Which of these cloud deployment models would BEST describe a company that would build a cloud for their own use and use systems and storage platforms in their data center?", "Private"),
("Which of the following malware types would cause a workstation to participate in a DDoS?", "Bot"),
("Which of these are used to force the preservation of data for later use in court?", "Legal hold"),
("A network administrator is installing a series of access points in a public library. Which of the following would be the BEST way to prevent theft of his laptop while performing this work?", "Cable lock"),
("A company would like to install an IPS to observe normal network activity and block any traffic that deviates from this baseline. Which of these IPS types would be the BEST fit for this requirement?", "Anomaly-based"),
("A security engineer is capturing packets on an internal company network and is documenting the IP addresses and MAC addresses associated with the local network devices. Which of these commands would provide the MAC address of the default gateway at 10.11.1.1?", "arp -a"),
("A network administrator needs to identify all inbound connections to a Linux web server. Which of the following utilities would be the BEST choice for this task?", "netstat"),
("A company has identified a web server data breach that resulted in the theft of financial records from 150 million customers. A security update to the company’s web server software was available for two months prior to the breach. Which of the following would have prevented this breach from occurring?", "Patch management"),
("A security administrator is deploying a web server and needs to understand the methods an attacker could use to gain access to the system. Which of the following would be the BEST source of this information?", "MITRE ATT&CK"),
("A system administrator has identified an unexpected username on a database server, and the user has been transferring database files to an external server over the company’s Internet connection. The administrator then performed these tasks: Physically disconnected the Ethernet cable on the database server, Disabled the unknown account, Configured a firewall rule to prevent file transfers from the server. Which of the following would BEST describe this part of the incident response process?", "Containment"),
("Which of the following would be the MOST effective use of asymmetric encryption?", "Securely derive a session key"),
("Each salesperson in a company will receive a laptop with applications and data to support their sales efforts. The IT manager would like to prevent third-parties from gaining access to this information if the laptop is stolen. Which of the following would be the BEST way to protect this data?", "Full disk encryption"),
("During sales meetings, visitors often require an Internet connection for demonstrations. Which of the following should the company implement to maintain the security of the internal network resources?", "Guest network with captive portal"),
("A company's web server has been infected with malware, and the security administrator has contained the system and would like to create a bit-by-bit image of the server storage drive. Which of the following would be the BEST choice for this task?", "dd"),
("A set of corporate security policies is what kind of security control?", "Managerial"),
("Which of the following would be the MOST significant security concern when protecting against criminal syndicates?", "Maintain reliable backup data"),
("An application team has been provided with a hardened version of Linux to use with a new application rollout, and they are installing a web service and the application code on the server. Which of the following would BEST protect the application from attacks?", "Implement a secure configuration of the web service"),
("A system administrator has configured MAC filtering on the corporate access point, but access logs show that unauthorized users are accessing the network. The administrator has confirmed that the address filter includes only authorized MAC addresses. Which of the following should the administrator configure to prevent this unauthorized use?", "Enable WPA3 encryption"),
("A company is building a broad set of conditional steps to follow when investigating a data breach. Which of the following would BEST describe these steps?", "Playbook"),
("During an initial network connection, a supplicant communicates to an authenticator, which then sends an authentication request to an Active Directory database. Which of the following would BEST describe this authentication technology?", "802.1X"),
("A security administrator would like use employee-owned mobile phones to unlock the door of the data center using a sensor on the wall. The users would authenticate on their phones with a fingerprint before the door would unlock. Which of the following features should the administrator use?", "NFC and Biometrics"),
("Visitors to a corporate data center must enter through the main doors of the building. Which of the following security controls would be the BEST choice to successfully guide people to the front door?", "Bollards and Fencing"),
("A company is contracting with a third-party to find vulnerabilities that employees could possibly exploit on the company’s internal networks. Which of the following would be the BEST way for the third-party to meet this requirement?", "Run a credentialed vulnerability scan"),
("A company has recently moved from one accounting system to another, and the new system includes integration with many other divisions of the organization. Which of the following would ensure that the correct access has been provided to the proper employees in each division?", "Permission and usage audit"),
("An attacker has circumvented a web-based application to send commands directly to a database. Which of the following would describe this attack type?", "SQL injection"),
("A group of business partners is using blockchain technology to monitor and track raw materials and parts as they are transferred between companies. Where would a partner find these tracking details?", "Ledger"),
("A network technician at a bank has noticed a significant decrease in traffic to the bank's public website. After additional investigation, the technician finds that users are being directed to a web site that looks similar to the bank's site but is not under the bank's control. Flushing the local DNS cache and changing the DNS entry does not have any effect. Which of the following has most likely occurred?", "Domain hijacking"),
("A company runs two separate applications in their data center. The security administrator has been tasked with preventing all communication between these applications. Which of the following would be the BEST way to implement this security requirement?", "Air gap"),
("A receptionist at a manufacturing company recently received an email from the CEO asking for a copy of the internal corporate employee directory. The receptionist replied to the email and attached a copy of the directory. It was later determined that the email address was not sent from the CEO and the domain associated with the email address was not a corporate domain name. What type of training could help prevent this type of situation in the future?", "Recognizing social engineering"),
("A company’s security engineer is working on a project to simplify the employee onboarding and offboarding process. One of the project goals is to allow individuals to use their personal phones for work purposes. If the user leaves the company, the company data will be removed but the user’s data would remain intact. Which of these technologies would meet this requirement?", "Containerization")
]




class FlashcardApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Flashcard Practice")
        self.root.geometry("1000x600")

        self.flashcard_frame = tk.Frame(self.root)
        self.flashcard_frame.pack(expand=True, fill=tk.BOTH)

        self.question_label = tk.Label(self.flashcard_frame, text="", wraplength=400, font=("Helvetica", 14))
        self.question_label.pack(pady=20)

        self.answer_label = tk.Label(self.flashcard_frame, text="", wraplength=400, font=("Helvetica", 14))
        self.answer_label.pack(pady=20)

        self.show_answer_button = tk.Button(self.flashcard_frame, text="Show Answer", command=self.show_answer)
        self.show_answer_button.pack(pady=10)

        self.next_button = tk.Button(self.flashcard_frame, text="Next", command=self.next_flashcard)
        self.next_button.pack(pady=10)

        self.flashcard_index = 0
        self.shuffle_flashcards()
        self.next_flashcard()

    def shuffle_flashcards(self):
        self.flashcard_indices = list(range(len(flashcards)))
        for i in range(len(self.flashcard_indices) - 1, 0, -1):
            j = i // 2
            self.flashcard_indices[i], self.flashcard_indices[j] = self.flashcard_indices[j], self.flashcard_indices[i]

    def next_flashcard(self):
        if self.flashcard_index >= len(self.flashcard_indices):
            self.flashcard_index = 0
        self.current_flashcard = flashcards[self.flashcard_indices[self.flashcard_index]]
        self.question_label.config(text=self.current_flashcard[0])
        self.answer_label.config(text="")
        self.flashcard_index += 1

    def show_answer(self):
        self.answer_label.config(text=self.current_flashcard[1])

if __name__ == "__main__":
    root = tk.Tk()
    app = FlashcardApp(root)
    root.mainloop()




